
services:
  postgres:
    image: postgres:16.4-alpine
    container_name: next_saas_starter_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # frontend:
  #   build: ./frontend
  #   image: nextjs-saas-starter:latest
  #   container_name: next_saas_starter_frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app

volumes:
  postgres_data:
